# Generated by Django 5.0.2 on 2024-03-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('donor', 'donor'), ('receiver', 'receiver')], max_length=255)),
                ('account_state', models.CharField(choices=[('initial', 'Initial'), ('completed', 'Completed')], default='initial', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('prof', 'Professional')], default='unknown', max_length=10)),
                ('profession', models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Lab', 'Lab'), ('Pharmacist', 'Pharmacist'), ('Administration', 'Administration'), ('unknown', 'Unknown')], max_length=15, null=True)),
                ('workplace_type', models.CharField(blank=True, choices=[('Hospital Private', 'Hospital Private'), ('Hospital Public', 'Hospital Public'), ('Private Clinic', 'Private Clinic'), ('Public Clinic', 'Public Clinic'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('workplace_name', models.TextField(blank=True, null=True)),
                ('workplace_address', models.TextField(blank=True, null=True)),
                ('donate_blood', models.CharField(blank=True, choices=[('once', 'Once'), ('regular', 'Regular'), ('never', 'Never'), ('unknown', 'Unknown')], max_length=7, null=True)),
                ('rare_blood_num', models.PositiveIntegerField(blank=True, null=True)),
                ('rare_blood_measure', models.CharField(blank=True, max_length=20, null=True)),
                ('allergic', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], max_length=7, null=True)),
                ('allergic_details', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], max_length=7, null=True)),
                ('permanent_cond', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('temp', 'Temporary'), ('unknown', 'Unknown')], max_length=7, null=True)),
                ('add_info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('donate_blood', models.CharField(choices=[('once', 'Once'), ('regular', 'Regular'), ('never', 'Never'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('anemic', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('infectious', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('infectious_details', models.TextField(blank=True, null=True)),
                ('hib', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('none', 'None'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('heart', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('pregnant', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('diabetic', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('pp', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
