# Generated by Django 5.0.2 on 2024-03-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('completed', 'Completed')], default='initial', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
    ]
