# Generated by Django 5.0.2 on 2024-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='profession',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab'), ('pharmacist', 'Pharmacist'), ('administration', 'Administration'), ('unknown', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='workplace_type',
            field=models.CharField(blank=True, choices=[('hospital_private', 'Hospital Private'), ('hospital_public', 'Hospital Public'), ('private_clinic', 'Private Clinic'), ('public_clinic', 'Public Clinic'), ('unknown', 'Unknown')], max_length=16, null=True),
        ),
    ]
