# Generated by Django 5.0.2 on 2024-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_state',
            field=models.CharField(choices=[('initial', 'initial'), ('completed', 'completed')], default='initial', max_length=255),
        ),
    ]
