# Generated by Django 5.0.2 on 2024-03-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.donor')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.receiver')),
            ],
        ),
    ]
