# Generated by Django 5.0.2 on 2024-03-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0001_initial'),
        ('users', '0007_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asks',
            new_name='Ask',
        ),
    ]
