# Generated by Django 5.0.2 on 2024-03-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='proposed_blood_type',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=7),
        ),
    ]
