# Generated by Django 5.0.2 on 2024-03-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0002_rename_asks_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='donor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ask',
            name='needed_blood_type',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=7),
        ),
    ]
