# Generated by Django 5.0.2 on 2024-03-22 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0002_ask_proposed_blood_type'),
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donor'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.receiver'),
        ),
    ]
